import type { Metadata } from "next";
import { poppins, comforter_Brush } from "./fonts";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${poppins.className}` }>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
